name: Build and Upload Artifact

on:
  push:
    branches: ["main", "dev", "rewrite"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build the project
        run: |
          mkdir -p build/x86_64
          make -B
          mv ttype build/x86_64/ttype-x86_64

      - name: Upload artifact to GitHub Release
        uses: actions/upload-artifact@v4
        with:
          name: ttype-x86_64
          path: build/x86_64/ttype-x86_64
